CREATE TRIGGER UNKPTASK2
    AFTER INSERT ON SIGHTINGS
    FOR EACH ROW
    WHEN NEW.PERSON NOT IN (SELECT NAME FROM MEMBERS)
    BEGIN
        INSERT INTO MEMBERS VALUES
            (NEW.PERSON, NULL, 1);
    END;